### ISSUE TITLE
Swindon upgrade to tokio

### ISSUE THREAD

**Issue by kindermax** [swindon-rs/swindon#85]
Hi, what do you think about some codebase renovation? 
From what I see, swindon codebase has at least two major legacy problems:
- deprecated tokio-core dependency
- not using async/await syntax (it is probably a job for another PR )

There are 4 possible ways to update the codebase:

1. Update tokio-core to >=0.1.13, the release where internals was updated to use tokio https://github.com/tokio-rs/tokio-ore/commit/e1db2bb8d042fb9410f5e4085f487fb5bc8181b6 . Also update all tk_* libs. Then reiterate to replace tokio-core with tokio in all libs and swindon itself. Then update tokio to the latest release and refactor the codebase. This is the longest but least intrusive way. The downside is, it is a loooot of work.
2. Drop tokio-core at the first iteration and refactor the codebase and libs to use tokio 0.1 from the beginning. This will end up in less repetitive work but it might be harder to not break something.
3. Same as 2 but try to migrate to the latest tokio.
4. The hardest/intrusive way. I have not researched yet but since rust crate ecosystem grew, we probably can replace some of tk_* libs with alternative crates that already solve the same issues and are already built on top of recent tokio, thus no need to update tk_* libs.

Personally, I think about 2 or 3 option.

The approach would be bottom-top - first, upgrade all libs , then upgrade swindon itself.
- tk-listener
- tk-pool
- tk-sendfile
- tk-http
- self-meter-http
- ns-router

**Comment by tailhook** [comment]
Hi Max! Thank you for your interest.

tk-http can be replaced by hyper I think. I don't think others have any direct replacements. Maybe sendfile is included in hyper, but I'm not sure.

Unfortunately, this codebase is awfully old and I don't have any bandwidth to maintain it or to review PRs. So the best thing for anybody interested is probably to fork the project. Therefore I don't have any opinion on how to approach this renovation.

**Comment by kindermax** [comment]
Sure, I understand that. I'm okay with forking, and thanks for hyper suggestion. 
I researched a bit, and one question I would like to ask: is swindon a single-threaded async server or it would be okay to make it multhithreaded assuming that tokio has multithreaded async runtime?

**Comment by tailhook** [comment]
It's okay to make it multi-threaded. Some extra care should be taken to protect shared structures. But probably even if shared structures are under shared global lock it might be useful that IO is multi-threaded. And then some parts of the shared structures can gradually be made concurrent.

**Comment by kindermax** [comment]
Thanks for the info, closing the issue then.
